name: Deploy em Staging

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/saulocdemonte/desafio-lacrei-app:latest
          
      - name: Deploy no Servidor EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/saulocdemonte/desafio-lacrei-app:latest
            docker stop lacrei-container || true
            docker rm lacrei-container || true
            docker run -d \
              -p 80:3000 \
              -p 443:8443 \
              -v /etc/letsencrypt:/etc/letsencrypt:ro \
              --log-driver=awslogs \
              --log-opt awslogs-region=us-east-1 \
              --log-opt awslogs-group=lacrei-staging-logs \
              --log-opt awslogs-create-group=true \
              --name lacrei-container \
              ghcr.io/saulocdemonte/desafio-lacrei-app:latest

      - name: Validar Deploy de Staging (Smoke Test)
        run: |
          sleep 15
          curl -f https://saulo-devops-lacrei.duckdns.org/status