name: Deploy em Staging

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # ADICIONAMOS ESTA SEÇÃO DE PERMISSÕES
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKHOR_USERNAME }}
          password: ${{ secrets.DOCKHOR_PASSWORD }}
          
      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: saulocdemonte/desafio-lacrei-app:latest
          
      - name: Deploy no Servidor EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker pull saulocdemonte/desafio-lacrei-app:latest
            docker stop lacrei-container || true
            docker rm lacrei-container || true
            docker run -d \
              -p 80:3000 \
              -p 443:8443 \
              -v /etc/letsencrypt:/etc/letsencrypt:ro \
              --log-driver=awslogs \
              --log-opt awslogs-region=us-east-1 \
              --log-opt awslogs-group=lacrei-staging-logs \
              --log-opt awslogs-create-group=true \
              --name lacrei-container \
              saulocdemonte/desafio-lacrei-app:latest