name: Deploy em Produção

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    # ADICIONAMOS ESTA SEÇÃO DE PERMISSÕES
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKHOR_USERNAME }}
          password: ${{ secrets.DOCKHOR_PASSWORD }}
          
      - name: Build e Push da Imagem Docker com Tag de Versão
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: saulocdemonte/desafio-lacrei-app:${{ github.ref_name }}
          
      - name: Deploy no Servidor EC2 de Produção
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_PROD }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker pull saulocdemonte/desafio-lacrei-app:${{ github.ref_name }}
            docker stop lacrei-container || true
            docker rm lacrei-container || true
            docker run -d -p 80:3000 --name lacrei-container saulocdemonte/desafio-lacrei-app:${{ github.ref_name }}